lgbm:
  best_auc: 0.854473674828071
  parameter:
    bagging_fraction: 1.0
    bagging_freq: 3.0
    boosting: gbdt
    early_stopping_round: 100.0
    feature_fraction: 0.4
    learning_rate: 0.1
    metric: auc
    num_iterations: 1000.0
    num_leaves: 40.0
    objective: binary
    seed: 42.0
    verbose: -1.0
