bert:
  best_auc: 0.7861948785624323
  parameter:
    batch_size: 64.0
    drop_out: 0.38892546768384945
    hidden_dim: 16.0
    lr: 0.0001
    n_epochs: 100.0
    n_heads: 8.0
    n_layers: 1.0
catboost:
  best_auc: -1
  parameter: null
lastquery:
  best_auc: -1
  parameter: null
lgbm:
  best_auc: -1
  parameter: null
lightgcn:
  best_auc: -1
  parameter: null
lstm:
  best_auc: 0.7642891494017957
  parameter:
    batch_size: 512.0
    drop_out: 0.2727314073029609
    hidden_dim: 512.0
    lr: 0.001
    max_seq_len: 25.0
    n_epochs: 100.0
lstmattn:
  best_auc: 0.8255093143459634
  parameter:
    batch_size: 32.0
    drop_out: 0.26915160444058467
    graph_dim: 250.0
    hidden_dim: 512.0
    lr: 0.009731779805332918
    max_seq_len: 115.0
    n_layers: 1.0
    pos_int1: 1.0
    shuffle_n: 2.0
    use_res: 0.0
    window: 34.0
saint:
  best_auc: -1
  parameter: null
translstm_g:
  best_auc: -1
  parameter: null
