bert:
  best_auc: 0.7861948785624323
  parameter:
    batch_size: 64.0
    drop_out: 0.38892546768384945
    hidden_dim: 16.0
    lr: 0.0001
    n_epochs: 100.0
    n_heads: 8.0
    n_layers: 1.0
catboost:
  best_auc: -1
  parameter: null
lastquery:
  best_auc: -1
  parameter: null
lgbm:
  best_auc: -1
  parameter: null
lightgcn:
  best_auc: -1
  parameter: null
lstm:
  best_auc: 0.7642891494017957
  parameter:
    batch_size: 512.0
    drop_out: 0.2727314073029609
    hidden_dim: 512.0
    lr: 0.001
    max_seq_len: 25.0
    n_epochs: 100.0
lstmattn:
  best_auc: 0.7700055715859752
  parameter:
    batch_size: 32.0
    drop_out: 0.2240276820435132
    hidden_dim: 318.0
    lr: 0.0038132027810098674
    max_seq_len: 46.0
    n_layers: 2.0
    shuffle_n: 1.0
    use_res: 0.0
saint:
  best_auc: -1
  parameter: null
translstm_g:
  best_auc: -1
  parameter: null
